collections:
  installations:
    output: true

defaults:
  - scope:
      path: ""
      type: "installations"
    values:
      layout: "installation"
      permalink: /installations/:path
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:year/:month/:day/:title
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

url: michellesh.github.io

google_analytics: G-XTF2JCGHV6

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
