collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      permalink: /projects/:path
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:year/:month/:day/:title
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

url: michellesh.github.io

google_analytics: G-GC7LD3QDSX

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
