collections:
  installations:
    output: true
  projects:
    output: true
  project-sub-pages:
    output: true
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "installations"
    values:
      layout: "installation"
      permalink: /installations/:path
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      permalink: /projects/:title
  - scope:
      path: ""
      type: "project-sub-pages"
    values:
      layout: "project-sub-page"
      permalink: /projects/:title
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:title
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

url: michellesh.github.io

google_analytics: G-XTF2JCGHV6

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
